version: "3.2"

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
        - mysql
    ports:
        - 81:80
    environment:
        PMA_HOST: mysql
        MYSQL_ROOT_PASSWORD: admin
    networks:
        - wpsite

  php:
    build: ./app/php/
    volumes:
      - ./app/wordpress/src/:/var/www/html/
    networks:
      - wpsite

  httpd:
    build: ./app/httpd/
    depends_on:
      - php
      - mysql
    ports:
      - "80:80"
    volumes:
      - ./app/wordpress/src/:/var/www/html/
    networks:
      - wpsite

  mysql:
    image: mysql:5.6.40
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./app/wordpress/database/:/var/lib/mysql/
    networks:
      - wpsite

networks:
  wpsite: