#!/bin/bash

mysql_container=mysql
mysql_user=admin
mysql_password=admin
database_name=wordpressdb

if [ "$(docker ps -q -f name=$mysql_container)" ]
then
    echo ">> Exporting database from container..."

    (docker exec -i $mysql_container mysqldump -u $mysql_user \
                                                --password=$mysql_password \
                                                $database_name > ../database/schema.sql) &> /dev/null
    if [ $? -eq 0 ]; then
        echo "Done"
    else
        echo "Failed"
    fi
fi

echo ">> Building wordpress website..."
docker-compose up -d --build