version: "3.2"

services:
  phpmyadmin:
    container_name: phpmyadmin
    restart: always
    image: phpmyadmin/phpmyadmin
    depends_on:
        - mysql
    ports:
        - 81:80
    environment:
        PMA_HOST: mysql
        MYSQL_ROOT_PASSWORD: admin
    networks:
        - wpsite

  php:
    container_name: php
    restart: always
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ../wordpress/src/:/var/www/html/
    networks:
      - wpsite

  apache:
    container_name: apache
    restart: always
    build:
      context: .
      dockerfile: apache.dockerfile
    depends_on:
      - php
      - mysql
    ports:
      - "80:80"
    volumes:
      - ../wordpress/src/:/var/www/html/
      - ../config/apache.conf:/usr/local/apache2/conf/apache.conf
    networks:
      - wpsite

  mysql:
    container_name: mysql
    image: mysql:5.6.40
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      - wpsite
    volumes:
      - ../database/data:/var/lib/mysql
      - ../database:/docker-entrypoint-initdb.d

networks:
  wpsite: